alertmanager:
  config:
    global:
      resolve_timeout: 5m
      telegram_api_url: "https://api.telegram.org"

    route:
      receiver: telegram-bot

    receivers:
      - name: telegram-bot
        telegram_configs:
          - chat_id: 426994883
            bot_token: <token>
            api_url: "https://api.telegram.org"
            send_resolved: true
            parse_mode: Markdown
            message: |-
              {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }}
                *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}

serverFiles:
  alerting_rules.yml:
    groups:
      - name: postgresql
        rules:
          - alert: Storage overflow
            expr: pg_database_size_bytes > 7 * 1024 * 1024
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "High storage usage on table {{ $labels.datname }}"
