services:
    backend-postgres:
        image: postgres:16.4
        environment:
            POSTGRES_PASSWORD: password
        ports:
          - 5432

    backend-service:
        build: backend/
        ports:
          - 8000:8000

    frontend-service:
        build: frontend/
        ports:
          - 3000:3000
