services:
    backend:
        build: backend/
        command: python3 server.py
        ports:
          - 8000:8000

    frontend:
        build: frontend/
        command: python3 server.py
        ports:
          - 3000:3000
        depends_on:
          - backend
