name: CI/CD for Lab-4

on:
  push:
    branches: 
      - main
    paths:
      - 'labs/lab-4/**'
  pull_request:
    branches:
      - main
    paths:
      - 'labs/lab-4/**'

jobs:
  print_hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print hello
        run: echo "Hello world!"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          cd labs/lab-4
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd labs/lab-4
          python -m unittest test_model.py

      - name: Train model
        run: |
          cd labs/lab-4
          python train.py
